### ISSUE TITLE
Automated asset pipeline

### ISSUE THREAD

**Issue by dsaltares** [saltares/libgdxjam#1]
We need to automate packing assets into atlases and other processing that might need doing. No manually packing and saving into the right hierarchy.

Let's say we have:

```
assets
    characters
        leg.png
        arm.png
```

We wanna end up with:

```
assets
    characters
        leg.png
        arm.png
        characters.png
        characters.atlas
```

We might want to run the process as part of game startup and separately as a command line tool.

**Comment by AlbertoCejas** [comment]
Done in 82be8e2b69aa1c9250bf8fb71cb113c8cb0d8122
