### ISSUE TITLE
The camera follows the player

### ISSUE THREAD

**Issue by dsaltares** [saltares/libgdxjam#13]
Player following camera behaviour. This is the perfect [refefence video](https://www.youtube.com/watch?v=pdvCO97jOQk).

**Comment by dsaltares** [comment]
Right now we have 1-1 camera-target following.

**Comment by AlbertoCejas** [comment]
Now we have a focus rectangle, to be tweaked in gameplay test.
Closed in f72aa1b9043791cf6cab5a31c48cba2af7f88c56
