### ISSUE TITLE
Load Overlap2D levels

### ISSUE THREAD

**Issue by dsaltares** [saltares/libgdxjam#2]
We want to be able to load Overlap2D levels supporting:
- Textures
- Particles
- Physics
- Invisible objects
- Animations
- ...

All using our Ashley component/system infrastructure.

[Custom Overlap2D Runtime](http://overlap2d.com/data-api-creating-custom-runtime/).

**Comment by dsaltares** [comment]
This is blocked on #4.

**Comment by dsaltares** [comment]
We're missing physics and lights.

**Comment by dsaltares** [comment]
@AlbertoCejas can this be considered done?

**Comment by AlbertoCejas** [comment]
yes ;)
