### ISSUE TITLE
CCTV cameras

### ISSUE THREAD

**Issue by dsaltares** [saltares/libgdxjam#32]
The game will feature CCTV cameras the player has to avoid:
- In Overlap they're a composite: camera texture + directional light.
- Special loader plugin to add a `CctvComponent` to every library composite of name "cctv" or something (maybe pick a better name).
- `CctvCameraSystem` updates cameras' rotations and checks for the player being exposed.

What happens if the player is exposed?
- Automatic lose?
- Do cameras shoot?
- Enemies can find you (harder to implement)

**Comment by dsaltares** [comment]
First pass implemented in 4de64da66e730250cda3a2ec917605fdf45c4620

**Comment by AlbertoCejas** [comment]
Second pass impemented in 0233835e61901760905a435c5d98408fc1a57fcf
Character detection would be the next step
