### ISSUE TITLE
Overlap Scene Loader plugins

### ISSUE THREAD

**Issue by dsaltares** [saltares/libgdxjam#33]
Some entities we place in levels will need special components, specific to our game: cameras, enemies, prisoners...

We need scene loader plugins to add extra components to composites that have a particular name.

``` java
public interface OverlapLoaderPlugin {
    public void load(Entity entity, JsonValue value);
}

public class OverlapSceneLoader {
    void registerPlugin(String compositeName, OverlapLoaderPlugin plugin);
}
```

**Comment by AlbertoCejas** [comment]
done in 4de64da66e730250cda3a2ec917605fdf45c4620
