### ISSUE TITLE
Ashley component/system collection

### ISSUE THREAD

**Issue by dsaltares** [saltares/libgdxjam#4]
Basic collection of Ashley components and system to support the Overlap2D feature set. We will have to tweak them in the future to adapt it to the game needs.

**Comment by dsaltares** [comment]
@AlbertoCejas Can this be considered done?

**Comment by AlbertoCejas** [comment]
Considering your feature description warning:
_We will have to tweak them in the future to adapt it to the game needs._

Yes :)
